### ISSUE TITLE
USGS node still use "old" ontology

### ISSUE THREAD

**Issue by denevers** [NRCan/GSIP#59]
for example

https://cida-test.er.usgs.gov/chyld-pilot/info/LOD_Node/US_Hydro_LOD_Node
https://cida-test.er.usgs.gov/chyld-pilot/info/hu/041504040205

don't have any representations because the repository still uses `rdfs:seeAlso` instead of `schemas:subjectOf` and node information is not correct either

**Comment by dblodgett-usgs** [comment]
I was confused by all the git conflicts and was just happy to get the new Java code working. The configuration of this is a bit painful. 

I have three functions here -- are you saying I should be using schema.org:subjectOf instead of rdfs:seeAlso? I do this in this function now: https://github.com/dblodgett-usgs/chyld_pilot_data_prep/blob/master/rdf_utils.R#L62

What specifically is wrong with the node information? I create all that stuff in here: https://github.com/dblodgett-usgs/chyld_pilot_data_prep/blob/master/node.R and honestly have no recollection of why it is the way it is!

**Comment by denevers** [comment]
>I have three functions here -- are you saying I should be using schema.org:subjectOf instead of rdfs:seeAlso? 

yes - this is the ontology we agreed on in Quebec

The node data in node.ttl says that your subject of (content) is our node.

**Comment by denevers** [comment]
I'm not sure you code will generate proper SELFIE datasets - we changed a couple of predicates (that was the whole discussion in Quebec)

**Comment by dblodgett-usgs** [comment]
Right -- I wasn't in Quebec. Do you know what else changed?

**Comment by denevers** [comment]
all your dataset should have this form

https://github.com/opengeospatial/SELFIE/blob/master/docs/examples/rdf/meta-resource-2.ttl

**Comment by dblodgett-usgs** [comment]
Right -- yeah that's what I was going to look to. I'll get to this later today hopefully.

**Comment by dblodgett-usgs** [comment]
I think this is fixed now. I don't have "conformsTo" or "provider" content, but these pages look right?

https://cida-test.er.usgs.gov/chyld-pilot/info/hu/041504081604
https://cida-test.er.usgs.gov/chyld-pilot/id/LOD_Node/US_Hydro_LOD_Node

Data pipeline update: https://github.com/dblodgett-usgs/chyld_pilot_data_prep/commit/9d04b4d06f79fb3b84fbeb33c024e268a8da63ea

I deployed this version of the app:
https://github.com/dblodgett-usgs/GSIP/tree/java11
